### ISSUE TITLE
[BUG] Not possible to enable faders

### ISSUE THREAD

**Issue by Jbithell** [Paradise-Pi/ParadisePi#103]
Faders are all permanently disabled - selecting enabled/disabled in admin does nothing on front end 

@cherry-john do you think this might relate to that Mantine update?

**Comment by cherry-john** [comment]
> Faders are all permanently disabled - selecting enabled/disabled in admin does nothing on front end 
> 
> @cherry-john do you think this might relate to that Mantine update?

Quite possibly, happy to have a look today
