### ISSUE TITLE
[DOCS] Autostart

### ISSUE THREAD

**Issue by nathanbillis** [Paradise-Pi/ParadisePi#23]
Add to docs how to autostart. I had a /bin/bash script which I followed this [forum post](https://forums.raspberrypi.com/viewtopic.php?t=294014) and navigated to: ``` nano /home/pi/.config/lxsession/LXDE-pi/autostart ``` then ```@bash /path/my_script```

**Comment by Jbithell** [comment]
Should probably also document hiding the cursor
